# Файл docker-compose.yml
version: '3'

volumes:
  pg_data_production:
  media_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  
  backend:
    image: ovip9u/fg_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_production:/media/images
  
  frontend:
    image: ovip9u/fg_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: ovip9u/fg_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_production:/media/images
    ports:
      - 8000:80