# Generated by Django 4.2.7 on 2023-11-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField()),
                ('author', models.TextField()),
                ('ingredients', models.TextField()),
                ('is_favorited', models.TextField()),
                ('is_in_shopping_cart', models.TextField()),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('text', models.TextField()),
                ('cooking_time', models.TextField()),
            ],
        ),
    ]
