# Generated by Django 4.2 on 2023-12-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_favorite_unique_favorite_user_recipe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
