# Generated by Django 5.0 on 2023-12-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Связь рецепт-ингредиент', 'verbose_name_plural': 'Связь рецепт-ингредиент'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Связь тег-рецепт', 'verbose_name_plural': 'Связь тег-рецепт'},
        ),
    ]
