# Generated by Django 4.2 on 2023-12-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=150, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
